const webpack = require("webpack");
const path = require("path");
const CopyWebpackPlugin = require("copy-webpack-plugin");
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const AssetsPlugin = require("assets-webpack-plugin");
const HtmlWebpackPlugin = require("html-webpack-plugin");

<html lang="TH">

<head>
  
  <script type="application/ld+json">
    {
      "@context": "https://schema.org",
      "@type": "Article",
      "mainEntityOfPage": {
        "@type": "WebPage",
        "@id": "https://mvpregisterwebtong.netlify.app/"
      },
      "headline": "สมัครเว็บตรง ของดีไม่ผ่านเอเย่นต์ ที่นี่ฝากไม่มีขั้นต่ำมีค่ายสล็อตดัง pg ให้บริการ",
      "image": "https://i.postimg.cc/bwttJqjx/06.jpg",  
      "InLanguage": "TH",    
      "keywords": "สมัครเว็บตรง",    
      "description": "ท่านนักพนันใดที่สนใจต้องการ สมัคเว็บตรงที่เพลิน มีโปรโมชั่นฟรีเครดิต ในเครือของufabet และ sbobet เป็นมิตรกับนักเล่นทุกคนต้องจัดที่เว็บเราเท่านั้น",  
      "author": {
        "@type": "Person",
        "name": "southblade"
      },  
      "publisher": {
        "@type": "Organization",
        "name": "",
        "logo": {
          "@type": "ImageObject",
          "url": ""
        }
      },
      "datePublished": "2023-01-15"
    }
    
    </script>



  <!--FAQPage Code Generated by https://saijogeorge.com/json-ld-schema-generator/faq/--></head>
module.exports = {
  entry: {
    main: path.join(__dirname, "src", "index.js"),
    cms: path.join(__dirname, "src", "js", "cms.js"),
  },

  output: {
    path: path.join(__dirname, "dist"),
    publicPath: ""
  },

  module: {
    rules: [
      {
        test: /\.((png)|(eot)|(woff)|(woff2)|(ttf)|(svg)|(gif))(\?v=\d+\.\d+\.\d+)?$/,
        loader: "file-loader",
        options: {
          name: "name=/[hash].[ext]"
        }
      },
      {
        loader: "babel-loader",
        test: /\.js?$/,
        exclude: /node_modules/,
        options: {cacheDirectory: true}
      },
      {
        test: /\.(sa|sc|c)ss$/,
        exclude: /node_modules/,
        use: [
          "style-loader", 
          {
            loader: MiniCssExtractPlugin.loader,
            options: {
              esModule: false
            }
          }, 
          "css-loader",
          "postcss-loader",
          "sass-loader"
        ]
      }
    ]
  },

  plugins: [
    new AssetsPlugin({
      filename: "webpack.json",
      path: path.join(process.cwd(), "site/data"),
      prettyPrint: true
    }),
    new CopyWebpackPlugin({
      patterns: [{
        from: "./src/fonts/",
        to: "fonts/",
      }]
    }),
    new HtmlWebpackPlugin({
      filename: "admin/index.html",
      template: 'src/cms.html',
      inject: true,
    })
  ]
};
