baseURL = "https://www.mvpdlc.com/"
title = "เว็บพนันออนไลน์ เว็บตรงไม่ผ่านเอเย่นต์ เว็บฝากถอนผ่านวอเลท 2023"

languageCode = "TH"
DefaultContentLanguage = "TH"
paginate = 12

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

[params]
  author = "Praveen Juge"
  github = "https://github.com/praveenjuge"
  facebook = "https://facebook.com/praveenjuge"
  og_image = "/images/og.png"
  sitename = "MVPDLC"
  twitter = "@praveenjuge"

[languages]
  [languages.th]
    languageName = "Thai"
    languageCode = "th"
    weight = 1

  [languages.ae]
    languageName = "Arabic"
    languageCode = "ae"
    weight = 2